### ISSUE TITLE
Conflict gestures

### ISSUE THREAD

**Issue by Ramink78** [dokar3/draggable-menu#4]
Hi, I use this composable in a BottomSheet and the problem occurs when dragging down in the menu, the BottomSheet consumes this gesture and it begins to collapse state

**Comment by dokar3** [comment]
Thanks for the feedback, will check this later.

**Comment by dokar3** [comment]
#6 should fix this issue.

**Comment by Ramink78** [comment]
Thanks for fixing this issue.
